version: '3.8'
services:
  backend:
    build:
      context: ../todo-app-springboot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todo_app_bbdd
      - SPRING_DATASOURCE_USERNAME=todo_app
      - SPRING_DATASOURCE_PASSWORD=todo_app
    depends_on:
      - db
    networks:
      - todo-network

  frontend:
    build:
      context: ../todo-app-react
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - todo-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=todo_app_bbdd
      - POSTGRES_USER=todo_app
      - POSTGRES_PASSWORD=todo_app
    ports:
      - "5001:5432" # Expongo el puerto en otro distinto para no confundirlo con el que tengo en mi local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge